name: Ocean Outcomes 
description:

markdown: redcarpet
highlighter: pygments
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]

baseurl: ''
port: 4000
# url:

twitter_handle: 

# Permalink Configuration
permalink: /:year/:month/:title

exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md', 'config.rb', 'assets/sass',  'node_modules', 'Procfile']

#Setting relative permalink to false. See http://jekyllrb.com/docs/upgrading/.
relative_permalinks: false

# Plugin config
gems: [jekyll-i18n]

# Assets config
sass:
  sass_dir: assets/sass

